#ifndef DEFINITION
#define DEFINITION

#define VERTEX_CHARACTER 'v'
#define NORMAL_CHARACTER 'n'
#define TEXTURE_CHARACTER 't'
#define PARAMETER_SPACE_CHARACTER 'p'
#define FACE_ELEMENT_CHARACTER 'f'
#define FILL_CHARACTER '0'
#define DELIMITER_CHARACTER '/'
#define COMMENT_CHARACTER '#'
#define OBJECT_FILE_EXTENSION ".obj"
#define DATA_FILE_EXTENSION ".dat"
#define DETECTION_METHOD_COUNT 2
#define ELEMENT_COUNT_2D 2
#define ELEMENT_COUNT_3D 3
#define EDGE_ELEMENT_COUNT 2
#define TRIANGLE_ELEMENT_COUNT 3
#define QUADRILATERAL_ELEMENT_COUNT 4
#define PENTAGON_ELEMENT_COUNT 5
#define HEXAGON_ELEMENT_COUNT 6
#define TETRAHEDRON_ELEMENT_COUNT 4
#define EXTREME_ELEMENT_COUNT 2
#define GRID_VERTEX_COUNT_2D 4
#define GRID_VERTEX_COUNT_3D 8
#define GRID_EDGE_COUNT_2D 4
#define GRID_EDGE_COUNT_3D 12
#define GRID_SURFACE_COUNT_2D 1
#define GRID_SURFACE_COUNT_3D 6
#define DIRECTION_COUNT_2D 4
#define DIRECTION_COUNT_3D 8
#define INITIAL_SURFACE_COUNT 2
#define ADDITIONAL_SURFACE_COUNT 3
#define DELIMITER_COUNT 2
#define EXTRA_COEFFICIENT_COUNT_2D 3
#define EXTRA_COEFFICIENT_COUNT_3D 4
#define DEGREE 2
#define DIGIT 2
#define INDICATOR_CONVENTIONAL_METHOD 0
#define INDICATOR_PROPOSED_METHOD 1
#define INDICATOR_X 0
#define INDICATOR_Y 1
#define INDICATOR_Z 2
#define INDICATOR_MINIMUM 0
#define INDICATOR_MAXIMUM 1
#define SPECIAL_PATTERN_A 5U
#define SPECIAL_PATTERN_B 10U
#define BORDER_SIZE 2

#endif